# ------------SERVER-CONFIG----------------
server.host = 26.198.98.181
server.port = 8888

#----------------DATABASE-CONFIG------------------
db.url = jdbc:mysql://4Fh6tercQZ88ojp.root:Pcw7mel45GAdVwvl@gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com:4000/Bidding?sslMode=VERIFY_IDENTITY
db.username = 4Fh6tercQZ88ojp.root
db.password = Pcw7mel45GAdVwvl