package shared.enums;

public enum Action {
    /**
     * Xác thực
     */
    LOGIN,
    REGISTER,
    LOGOUT,

    /**
    *  Ví
    */
    GET_WALLET,
    DEPOSIT_WALLET,

    /**
     * Seller
     */
    CREATE_ITEM,
    UPDATE_ITEM,
    DELETE_ITEM,
    GET_SELLER_ITEMS,
    SEND_CREATE_AUCTION_REQUEST,


    /**
     * Bidder
     */
    GET_WON_AUCTIONS,
    PLACE_BID,
    SUBSCRIBE_AUCTION,
    UNSUBSCRIBE_AUCTION,

    REGISTER_AUTO_BID_RULE,
    REMOVE_AUTO_BID_RULE,
    GET_AUTO_BID_RULE,

    /**
     * Admin
     */
    GET_USERS_LIST,
    ENABLE_USER,
    DISABLE_USER,
    GET_CREATE_AUCTION_REQUESTS,
    ACCEPT_CREATE_AUCTION_REQUEST,
    REJECT_CREATE_AUCTION_REQUEST,
    GET_ALL_AUCTIONS,
    GET_ALL_ITEMS,

    GET_BID_HISTORY,
    GET_AUCTION_LIST,
    GET_AUCTION_DETAILS,
    GET_USER_PROFILE,
    UPDATE_USER_PROFILE,
    GET_LEADERBOARD,
    GET_NOTIFICATIONS,
    SUBSCRIBE_AUCTION_LIST,
    UNSUBSCRIBE_AUCTION_LIST,
    GET_ADMIN_DASHBOARD_STATS,
}