package shared.enums;

public enum Action {
    LOGIN,
    REGISTER,
    LOGOUT,
    PLACE_BID,
    GET_BID_HISTORY,
    JOIN_AUCTION,
    LEAVE_AUCTION,
    GET_AUCTION_LIST,
    GET_AUCTION_DETAILS,
    GET_USER_PROFILE,
    UPDATE_USER_PROFILE,
    GET_LEADERBOARD,
    GET_NOTIFICATIONS,
    SUBSCRIBE_AUCTION,
    UNSUBSCRIBE_AUCTION,
    HEARTBEAT
}
